import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import ts from "typescript";

const FEATURE_IDS = [
	"dinkus.cta-band",
	"dinkus.page-hero",
	"dinkus.section-header",
	"dinkus.fact-rail",
	"dinkus.gallery-hero",
	"dinkus.ledger-cards",
	"dinkus.gallery-lanes",
	"dinkus.search-board",
	"dinkus.service-area-map",
	"dinkus.dispatch",
	"dinkus.project-record",
];

const FEATURE_SHARED_DEPENDENCIES = new Map([
	[
		"cta-band",
		new Set(["src/shared/links.ts", "src/shared/portable-text.ts"]),
	],
]);

const GOVERNED_EXTENSIONS = new Set([
	".astro",
	".cjs",
	".css",
	".js",
	".json",
	".jsonc",
	".jsx",
	".mjs",
	".mts",
	".scss",
	".toml",
	".ts",
	".tsx",
	".yaml",
	".yml",
]);

const ROOT_CONFIGURATION_FILES = new Set([
	"package.json",
	"playwright.config.ts",
	"pnpm-lock.yaml",
	"pnpm-workspace.yaml",
	"tsconfig.json",
	"vitest.config.ts",
]);

function lineNumber(source, offset) {
	return source.slice(0, offset).split("\n").length;
}

function normalizePath(value) {
	return value.replaceAll("\\", "/").replace(/^\.\//, "");
}

function walkFiles(root, start) {
	const absoluteStart = resolve(root, start);
	try {
		if (!statSync(absoluteStart).isDirectory()) return [];
	} catch {
		return [];
	}

	const files = [];
	const pending = [absoluteStart];
	while (pending.length > 0) {
		const current = pending.pop();
		for (const entry of readdirSync(current, { withFileTypes: true })) {
			if (
				entry.name === "node_modules" ||
				entry.name === ".artifacts" ||
				entry.name === ".astro" ||
				entry.name === "dist" ||
				entry.name === "coverage"
			) {
				continue;
			}
			const absolute = join(current, entry.name);
			if (entry.isDirectory()) pending.push(absolute);
			if (entry.isFile()) files.push(normalizePath(relative(root, absolute)));
		}
	}
	return files;
}

export function governedFiles(root) {
	const files = [
		...walkFiles(root, "src"),
		...walkFiles(root, "tests"),
		...walkFiles(root, "scripts"),
		...walkFiles(root, "bin"),
		...walkFiles(root, ".github/workflows"),
	];
	for (const file of ROOT_CONFIGURATION_FILES) {
		try {
			if (statSync(resolve(root, file)).isFile()) files.push(file);
		} catch {
			continue;
		}
	}
	return [...new Set(files)]
		.filter(
			(file) =>
				GOVERNED_EXTENSIONS.has(extname(file)) || file === "bin/verify-blocks",
		)
		.sort();
}

function allowedComment(path, text, offset) {
	if (
		path.endsWith(".d.ts") &&
		/^\/\/\/ <reference types="[a-zA-Z0-9@/_-]+" \/>$/.test(text)
	) {
		return true;
	}
	if (
		path === "tests/fixture-site/emdash-env.d.ts" &&
		(text === "// Generated by EmDash on dev server start" ||
			text === "// Do not edit manually")
	) {
		return true;
	}
	return (
		path === "bin/verify-blocks" &&
		offset === 0 &&
		text === "#!/usr/bin/env node"
	);
}

function scriptComments(path, source, sourceOffset = 0) {
	const tree = ts.createSourceFile(path, source, ts.ScriptTarget.Latest, true);
	const ranges = new Map();
	const collectAt = (position) => {
		if (typeof position !== "number") return;
		for (const reader of [ts.getLeadingCommentRanges, ts.getTrailingCommentRanges]) {
			for (const range of reader(source, position) ?? []) {
				ranges.set(`${range.pos}:${range.end}`, range);
			}
		}
	};
	const visit = (node) => {
		collectAt(node.fullStart);
		collectAt(node.pos);
		collectAt(node.end);
		ts.forEachChild(node, visit);
	};
	visit(tree);
	if (source.startsWith("#!")) {
		const end = source.indexOf("\n");
		ranges.set(`0:${end === -1 ? source.length : end}`, {
			pos: 0,
			end: end === -1 ? source.length : end,
		});
	}
	const findings = [];
	for (const range of [...ranges.values()].sort((left, right) => left.pos - right.pos)) {
		const offset = sourceOffset + range.pos;
		const text = source.slice(range.pos, range.end);
		if (!allowedComment(path, text, offset)) {
			findings.push({ path, line: lineNumber(source, range.pos), text });
		}
	}
	return findings;
}

function quotedMarkerComments(path, source, markers) {
	const findings = [];
	let quote = "";
	let escaped = false;
	for (let index = 0; index < source.length; index += 1) {
		const character = source[index];
		if (quote) {
			if (escaped) escaped = false;
			else if (character === "\\") escaped = true;
			else if (character === quote) quote = "";
			continue;
		}
		const beforeQuote = source.slice(0, index);
		const quoteStartsValue =
			character === "`" ||
			index === 0 ||
			/(?:[=([{,:;!?&|+*%/-]|\b(?:await|case|return|throw|yield))\s*$/.test(
				beforeQuote,
			);
		if ((character === "\"" || character === "'" || character === "`") && quoteStartsValue) {
			quote = character;
			continue;
		}
		for (const marker of markers) {
			if (!source.startsWith(marker, index)) continue;
			const lineStart = source.lastIndexOf("\n", index - 1) + 1;
			const markerPrefix = source.slice(lineStart, index + marker.length);
			if (
				marker === "//" &&
				(source[index - 1] === "\\" ||
					/[a-z][a-z0-9+.-]*:\/\/[^\s"'`<>]*$/i.test(markerPrefix))
			) {
				continue;
			}
			const endMarker = marker === "/*" ? "*/" : marker === "<!--" ? "-->" : "\n";
			const end = source.indexOf(endMarker, index + marker.length);
			const stop = end === -1 ? source.length : end + (endMarker === "\n" ? 0 : endMarker.length);
			const text = source.slice(index, stop);
			if (!allowedComment(path, text, index)) {
				findings.push({ path, line: lineNumber(source, index), text });
			}
			index = Math.max(index, stop - 1);
			break;
		}
	}
	return findings;
}

function yamlComments(path, source) {
	const findings = [];
	for (const [lineIndex, line] of source.split("\n").entries()) {
		let quote = "";
		for (let index = 0; index < line.length; index += 1) {
			const character = line[index];
			if (quote) {
				if (character === quote && line[index - 1] !== "\\") quote = "";
				continue;
			}
			if (character === "\"" || character === "'") {
				quote = character;
				continue;
			}
			if (character === "#" && (index === 0 || /\s/.test(line[index - 1]))) {
				const text = line.slice(index);
				if (!allowedComment(path, text, source.indexOf(line) + index)) {
					findings.push({ path, line: lineIndex + 1, text });
				}
				break;
			}
		}
	}
	return findings;
}

function astroComments(path, source) {
	const findings = quotedMarkerComments(path, source, ["<!--", "/*", "//"]);
	if (!source.startsWith("---")) return findings;
	const closing = source.indexOf("\n---", 3);
	if (closing === -1) return findings;
	const frontmatterOffset = source.indexOf("\n") + 1;
	const frontmatter = source.slice(frontmatterOffset, closing);
	const frontmatterFindings = scriptComments(path, frontmatter, frontmatterOffset).map(
		(finding) => ({
			...finding,
			line: finding.line + lineNumber(source, frontmatterOffset) - 1,
		}),
	);
	const identities = new Set(
		frontmatterFindings.map((finding) => `${finding.line}:${finding.text}`),
	);
	return [
		...frontmatterFindings,
		...findings.filter(
			(finding) => !identities.has(`${finding.line}:${finding.text}`),
		),
	];
}

export function findCommentViolations(path, source) {
	const extension = extname(path);
	if (extension === ".astro") return astroComments(path, source);
	if (extension === ".yaml" || extension === ".yml" || extension === ".toml") {
		return yamlComments(path, source);
	}
	if (extension === ".css" || extension === ".scss") {
		return quotedMarkerComments(path, source, ["/*", "//"]);
	}
	return scriptComments(path, source);
}

function scriptSegments(path, source) {
	if (!path.endsWith(".astro")) return [source];
	if (!source.startsWith("---")) return [];
	const closing = source.indexOf("\n---", 3);
	if (closing === -1) return [];
	return [source.slice(source.indexOf("\n") + 1, closing)];
}

function moduleSpecifiers(path, source) {
	const specifiers = [];
	for (const segment of scriptSegments(path, source)) {
		const tree = ts.createSourceFile(path, segment, ts.ScriptTarget.Latest, true);
		const visit = (node) => {
			if (
				(ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
				node.moduleSpecifier &&
				ts.isStringLiteral(node.moduleSpecifier)
			) {
				specifiers.push(node.moduleSpecifier.text);
			}
			if (
				ts.isCallExpression(node) &&
				node.expression.kind === ts.SyntaxKind.ImportKeyword &&
				node.arguments.length === 1 &&
				ts.isStringLiteral(node.arguments[0])
			) {
				specifiers.push(node.arguments[0].text);
			}
			ts.forEachChild(node, visit);
		};
		visit(tree);
	}
	return specifiers;
}

function resolvedRepositoryPath(importer, specifier) {
	if (!specifier.startsWith(".")) return null;
	return normalizePath(join(dirname(importer), specifier));
}

function featureTarget(path) {
	const match = path.match(/^src\/features\/([^/]+)(?:\/(.*))?$/);
	if (!match) return null;
	return { id: match[1], remainder: match[2] ?? "" };
}

function featureOwner(path) {
	return path.match(/^src\/features\/([^/]+)\//)?.[1] ?? null;
}

function isFeatureEntry(remainder) {
	return remainder === "" || /^index(?:\.[cm]?[jt]sx?)?$/.test(remainder);
}

function isPackagePublicSpecifier(specifier) {
	return specifier === "@dinkuskit/blocks" || specifier === "@dinkuskit/blocks/astro";
}

export function findImportViolations(path, source) {
	const violations = [];
	for (const specifier of moduleSpecifiers(path, source)) {
		if (
			specifier.startsWith("@dinkuskit/blocks/") &&
			!isPackagePublicSpecifier(specifier)
		) {
			violations.push({ path, specifier, reason: "package consumers must use a declared public export" });
			continue;
		}
		const target = resolvedRepositoryPath(path, specifier);
		if (!target) continue;
		const owner = featureOwner(path);
		const targetFeature = featureTarget(target);
		if (targetFeature) {
			if (owner === targetFeature.id) continue;
			if (
				path === "src/astro/index.ts" &&
				targetFeature.remainder === "renderer.astro"
			) {
				continue;
			}
			if (!isFeatureEntry(targetFeature.remainder)) {
				violations.push({ path, specifier, reason: "feature internals are private outside their owner" });
			}
			continue;
		}
		if (owner && target.startsWith("src/shared/")) {
			const allowed = FEATURE_SHARED_DEPENDENCIES.get(owner) ?? new Set();
			const candidates = new Set([target, `${target}.ts`, `${target}.astro`]);
			if (![...candidates].some((candidate) => allowed.has(candidate))) {
				violations.push({ path, specifier, reason: "shared dependency is not declared for this feature" });
			}
			continue;
		}
		if (owner && target.startsWith("src/")) {
			violations.push({ path, specifier, reason: "features may use only their internals and declared shared dependencies" });
			continue;
		}
		if (path.startsWith("tests/") && target.startsWith("src/")) {
			const publicTargets = new Set([
				"src/index",
				"src/index.ts",
				"src/astro/index",
				"src/astro/index.ts",
			]);
			if (!publicTargets.has(target)) {
				violations.push({ path, specifier, reason: "test consumers must use a package public entry point" });
			}
		}
	}
	return violations;
}

function tableCells(line) {
	return line
		.slice(1, -1)
		.split("|")
		.map((cell) => cell.trim());
}

function codeSpans(value) {
	return [...value.matchAll(/`([^`]+)`/g)].map((match) => match[1]);
}

export function validateFeatureMap(root, source = readFileSync(resolve(root, "FEATURE_MAP.md"), "utf8")) {
	const errors = [];
	const lines = source.split("\n");
	const headerIndex = lines.findIndex((line) => line.startsWith("| Stable feature ID |"));
	if (headerIndex === -1) return ["FEATURE_MAP.md is missing the canonical feature table"];
	const rows = [];
	for (const line of lines.slice(headerIndex + 2)) {
		if (!line.startsWith("|")) break;
		rows.push(tableCells(line));
	}
	if (rows.length !== FEATURE_IDS.length) {
		errors.push(`expected ${FEATURE_IDS.length} feature rows, found ${rows.length}`);
	}
	const observed = [];
	for (const cells of rows) {
		if (cells.length !== 10) {
			errors.push(`feature row has ${cells.length} columns instead of 10: ${cells[0] ?? "unknown"}`);
			continue;
		}
		if (cells.some((cell) => cell.length === 0)) errors.push(`feature row has an empty field: ${cells[0]}`);
		const [id] = codeSpans(cells[0]);
		observed.push(id);
		if (cells[6] !== "`bin/verify-blocks quick`") errors.push(`${id} has a noncanonical quick verifier`);
		if (!cells[7].startsWith("`pnpm exec playwright test tests/e2e/")) {
			errors.push(`${id} is missing a focused browser proof command`);
		}
		for (const path of [...codeSpans(cells[2]), ...codeSpans(cells[3]), ...codeSpans(cells[5])]) {
			if (path.startsWith("@") || !path.includes("/")) continue;
			const cleanPath = path.endsWith("/") ? path.slice(0, -1) : path;
			try {
				statSync(resolve(root, cleanPath));
			} catch {
				errors.push(`${id} references missing path ${path}`);
			}
		}
	}
	if (new Set(observed).size !== observed.length) errors.push("feature IDs must be unique");
	for (const id of FEATURE_IDS) {
		if (!observed.includes(id)) errors.push(`feature map is missing ${id}`);
	}
	const migrated = rows.filter((cells) => cells[9] === "migrated pilot").map((cells) => codeSpans(cells[0])[0]);
	if (migrated.length !== 1 || migrated[0] !== "dinkus.cta-band") {
		errors.push("CTA Band must be the only migrated pilot");
	}
	return errors;
}

export function repositoryImportViolations(root) {
	return governedFiles(root).flatMap((path) => {
		if (!/[.](?:astro|[cm]?[jt]sx?)$/.test(path) && path !== "bin/verify-blocks") return [];
		return findImportViolations(path, readFileSync(resolve(root, path), "utf8"));
	});
}

export function repositoryCommentViolations(root) {
	return governedFiles(root).flatMap((path) =>
		findCommentViolations(path, readFileSync(resolve(root, path), "utf8")),
	);
}
